/*
 * generated by Xtext 2.25.0
 */
package modelConverter.use_language.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractUSEValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(modelConverter.use_language.use.UsePackage.eINSTANCE);
		return result;
	}
}
