/**
 * generated by Xtext 2.25.0
 */
package modelConverter.use_language.use;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>All Class</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see modelConverter.use_language.use.UsePackage#getAllClass()
 * @model
 * @generated
 */
public interface AllClass extends AllClassAndEnum
{
} // AllClass
