/**
 * generated by Xtext 2.25.0
 */
package modelConverter.use_language.use;

import org.eclipse.emf.ecore.EObject;

import org.eclipse.ocl.xtext.essentialoclcs.ExpCS;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Context CS</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link modelConverter.use_language.use.ContextCS#getOwnedExpression <em>Owned Expression</em>}</li>
 * </ul>
 *
 * @see modelConverter.use_language.use.UsePackage#getContextCS()
 * @model
 * @generated
 */
public interface ContextCS extends EObject
{
  /**
   * Returns the value of the '<em><b>Owned Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Expression</em>' containment reference.
   * @see #setOwnedExpression(ExpCS)
   * @see modelConverter.use_language.use.UsePackage#getContextCS_OwnedExpression()
   * @model containment="true"
   * @generated
   */
  ExpCS getOwnedExpression();

  /**
   * Sets the value of the '{@link modelConverter.use_language.use.ContextCS#getOwnedExpression <em>Owned Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Owned Expression</em>' containment reference.
   * @see #getOwnedExpression()
   * @generated
   */
  void setOwnedExpression(ExpCS value);

} // ContextCS
