/**
 * generated by Xtext 2.25.0
 */
package modelConverter.use_language.use;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Exp CS</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see modelConverter.use_language.use.UsePackage#getExpCS()
 * @model
 * @generated
 */
public interface ExpCS extends EObject
{
} // ExpCS
