/**
 * generated by Xtext 2.25.0
 */
package modelConverter.use_language.use;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Generalization</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link modelConverter.use_language.use.Generalization#getGeneral <em>General</em>}</li>
 * </ul>
 *
 * @see modelConverter.use_language.use.UsePackage#getGeneralization()
 * @model
 * @generated
 */
public interface Generalization extends EObject
{
  /**
   * Returns the value of the '<em><b>General</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>General</em>' reference.
   * @see #setGeneral(AllClass)
   * @see modelConverter.use_language.use.UsePackage#getGeneralization_General()
   * @model
   * @generated
   */
  AllClass getGeneral();

  /**
   * Sets the value of the '{@link modelConverter.use_language.use.Generalization#getGeneral <em>General</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>General</em>' reference.
   * @see #getGeneral()
   * @generated
   */
  void setGeneral(AllClass value);

} // Generalization
