/**
 * generated by Xtext 2.25.0
 */
package modelConverter.use_language.use;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Invalid Literal Exp CS</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see modelConverter.use_language.use.UsePackage#getInvalidLiteralExpCS()
 * @model
 * @generated
 */
public interface InvalidLiteralExpCS extends PrimitiveLiteralExpCS
{
} // InvalidLiteralExpCS
