/**
 * generated by Xtext 2.25.0
 */
package modelConverter.use_language.use;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model USE</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link modelConverter.use_language.use.ModelUSE#getName <em>Name</em>}</li>
 *   <li>{@link modelConverter.use_language.use.ModelUSE#getEnums <em>Enums</em>}</li>
 *   <li>{@link modelConverter.use_language.use.ModelUSE#getPackagedElement <em>Packaged Element</em>}</li>
 *   <li>{@link modelConverter.use_language.use.ModelUSE#getConstraints <em>Constraints</em>}</li>
 * </ul>
 *
 * @see modelConverter.use_language.use.UsePackage#getModelUSE()
 * @model
 * @generated
 */
public interface ModelUSE extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see modelConverter.use_language.use.UsePackage#getModelUSE_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link modelConverter.use_language.use.ModelUSE#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Enums</b></em>' containment reference list.
   * The list contents are of type {@link modelConverter.use_language.use.Enum}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Enums</em>' containment reference list.
   * @see modelConverter.use_language.use.UsePackage#getModelUSE_Enums()
   * @model containment="true"
   * @generated
   */
  EList<modelConverter.use_language.use.Enum> getEnums();

  /**
   * Returns the value of the '<em><b>Packaged Element</b></em>' containment reference list.
   * The list contents are of type {@link modelConverter.use_language.use.Type}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Packaged Element</em>' containment reference list.
   * @see modelConverter.use_language.use.UsePackage#getModelUSE_PackagedElement()
   * @model containment="true"
   * @generated
   */
  EList<Type> getPackagedElement();

  /**
   * Returns the value of the '<em><b>Constraints</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constraints</em>' containment reference.
   * @see #setConstraints(ConstrainsGeneral)
   * @see modelConverter.use_language.use.UsePackage#getModelUSE_Constraints()
   * @model containment="true"
   * @generated
   */
  ConstrainsGeneral getConstraints();

  /**
   * Sets the value of the '{@link modelConverter.use_language.use.ModelUSE#getConstraints <em>Constraints</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Constraints</em>' containment reference.
   * @see #getConstraints()
   * @generated
   */
  void setConstraints(ConstrainsGeneral value);

} // ModelUSE
