/**
 * generated by Xtext 2.25.0
 */
package modelConverter.use_language.use;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Multiplicity CS</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link modelConverter.use_language.use.MultiplicityCS#isIsNullFree <em>Is Null Free</em>}</li>
 * </ul>
 *
 * @see modelConverter.use_language.use.UsePackage#getMultiplicityCS()
 * @model
 * @generated
 */
public interface MultiplicityCS extends EObject
{
  /**
   * Returns the value of the '<em><b>Is Null Free</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Null Free</em>' attribute.
   * @see #setIsNullFree(boolean)
   * @see modelConverter.use_language.use.UsePackage#getMultiplicityCS_IsNullFree()
   * @model
   * @generated
   */
  boolean isIsNullFree();

  /**
   * Sets the value of the '{@link modelConverter.use_language.use.MultiplicityCS#isIsNullFree <em>Is Null Free</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Null Free</em>' attribute.
   * @see #isIsNullFree()
   * @generated
   */
  void setIsNullFree(boolean value);

} // MultiplicityCS
