/**
 * generated by Xtext 2.25.0
 */
package modelConverter.use_language.use;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Multiplicity Bounds CS</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link modelConverter.use_language.use.MultiplicityBoundsCS#getLowerBound <em>Lower Bound</em>}</li>
 *   <li>{@link modelConverter.use_language.use.MultiplicityBoundsCS#getUpperBound <em>Upper Bound</em>}</li>
 * </ul>
 *
 * @see modelConverter.use_language.use.UsePackage#getMultiplicityBoundsCS()
 * @model
 * @generated
 */
public interface MultiplicityBoundsCS extends MultiplicityCS
{
  /**
   * Returns the value of the '<em><b>Lower Bound</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lower Bound</em>' attribute.
   * @see #setLowerBound(String)
   * @see modelConverter.use_language.use.UsePackage#getMultiplicityBoundsCS_LowerBound()
   * @model
   * @generated
   */
  String getLowerBound();

  /**
   * Sets the value of the '{@link modelConverter.use_language.use.MultiplicityBoundsCS#getLowerBound <em>Lower Bound</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lower Bound</em>' attribute.
   * @see #getLowerBound()
   * @generated
   */
  void setLowerBound(String value);

  /**
   * Returns the value of the '<em><b>Upper Bound</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Upper Bound</em>' attribute.
   * @see #setUpperBound(String)
   * @see modelConverter.use_language.use.UsePackage#getMultiplicityBoundsCS_UpperBound()
   * @model
   * @generated
   */
  String getUpperBound();

  /**
   * Sets the value of the '{@link modelConverter.use_language.use.MultiplicityBoundsCS#getUpperBound <em>Upper Bound</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Upper Bound</em>' attribute.
   * @see #getUpperBound()
   * @generated
   */
  void setUpperBound(String value);

} // MultiplicityBoundsCS
