/**
 * generated by Xtext 2.25.0
 */
package modelConverter.use_language.use;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Multiplicity String CS</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link modelConverter.use_language.use.MultiplicityStringCS#getStringBounds <em>String Bounds</em>}</li>
 * </ul>
 *
 * @see modelConverter.use_language.use.UsePackage#getMultiplicityStringCS()
 * @model
 * @generated
 */
public interface MultiplicityStringCS extends MultiplicityCS
{
  /**
   * Returns the value of the '<em><b>String Bounds</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>String Bounds</em>' attribute.
   * @see #setStringBounds(String)
   * @see modelConverter.use_language.use.UsePackage#getMultiplicityStringCS_StringBounds()
   * @model
   * @generated
   */
  String getStringBounds();

  /**
   * Sets the value of the '{@link modelConverter.use_language.use.MultiplicityStringCS#getStringBounds <em>String Bounds</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>String Bounds</em>' attribute.
   * @see #getStringBounds()
   * @generated
   */
  void setStringBounds(String value);

} // MultiplicityStringCS
