/**
 * generated by Xtext 2.25.0
 */
package modelConverter.use_language.use;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operation Constraints</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link modelConverter.use_language.use.OperationConstraints#getOperationDeclaration <em>Operation Declaration</em>}</li>
 *   <li>{@link modelConverter.use_language.use.OperationConstraints#getConditions <em>Conditions</em>}</li>
 * </ul>
 *
 * @see modelConverter.use_language.use.UsePackage#getOperationConstraints()
 * @model
 * @generated
 */
public interface OperationConstraints extends EObject
{
  /**
   * Returns the value of the '<em><b>Operation Declaration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operation Declaration</em>' containment reference.
   * @see #setOperationDeclaration(OperationDeclaration)
   * @see modelConverter.use_language.use.UsePackage#getOperationConstraints_OperationDeclaration()
   * @model containment="true"
   * @generated
   */
  OperationDeclaration getOperationDeclaration();

  /**
   * Sets the value of the '{@link modelConverter.use_language.use.OperationConstraints#getOperationDeclaration <em>Operation Declaration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operation Declaration</em>' containment reference.
   * @see #getOperationDeclaration()
   * @generated
   */
  void setOperationDeclaration(OperationDeclaration value);

  /**
   * Returns the value of the '<em><b>Conditions</b></em>' containment reference list.
   * The list contents are of type {@link modelConverter.use_language.use.ConditionType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conditions</em>' containment reference list.
   * @see modelConverter.use_language.use.UsePackage#getOperationConstraints_Conditions()
   * @model containment="true"
   * @generated
   */
  EList<ConditionType> getConditions();

} // OperationConstraints
