/**
 * generated by Xtext 2.25.0
 */
package modelConverter.use_language.use;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pattern Exp CS</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link modelConverter.use_language.use.PatternExpCS#getPatternVariableName <em>Pattern Variable Name</em>}</li>
 *   <li>{@link modelConverter.use_language.use.PatternExpCS#getOwnedPatternType <em>Owned Pattern Type</em>}</li>
 * </ul>
 *
 * @see modelConverter.use_language.use.UsePackage#getPatternExpCS()
 * @model
 * @generated
 */
public interface PatternExpCS extends EObject
{
  /**
   * Returns the value of the '<em><b>Pattern Variable Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pattern Variable Name</em>' attribute.
   * @see #setPatternVariableName(String)
   * @see modelConverter.use_language.use.UsePackage#getPatternExpCS_PatternVariableName()
   * @model
   * @generated
   */
  String getPatternVariableName();

  /**
   * Sets the value of the '{@link modelConverter.use_language.use.PatternExpCS#getPatternVariableName <em>Pattern Variable Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pattern Variable Name</em>' attribute.
   * @see #getPatternVariableName()
   * @generated
   */
  void setPatternVariableName(String value);

  /**
   * Returns the value of the '<em><b>Owned Pattern Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Pattern Type</em>' containment reference.
   * @see #setOwnedPatternType(TypedRefCS)
   * @see modelConverter.use_language.use.UsePackage#getPatternExpCS_OwnedPatternType()
   * @model containment="true"
   * @generated
   */
  TypedRefCS getOwnedPatternType();

  /**
   * Sets the value of the '{@link modelConverter.use_language.use.PatternExpCS#getOwnedPatternType <em>Owned Pattern Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Owned Pattern Type</em>' containment reference.
   * @see #getOwnedPatternType()
   * @generated
   */
  void setOwnedPatternType(TypedRefCS value);

} // PatternExpCS
