/**
 * generated by Xtext 2.25.0
 */
package modelConverter.use_language.use;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Precondition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see modelConverter.use_language.use.UsePackage#getPrecondition()
 * @model
 * @generated
 */
public interface Precondition extends ConditionType
{
} // Precondition
