/**
 * generated by Xtext 2.25.0
 */
package modelConverter.use_language.use;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Self Exp CS</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see modelConverter.use_language.use.UsePackage#getSelfExpCS()
 * @model
 * @generated
 */
public interface SelfExpCS extends ExpCS
{
} // SelfExpCS
