/**
 * generated by Xtext 2.25.0
 */
package modelConverter.use_language.use.impl;

import modelConverter.use_language.use.CollectionTypeCS;
import modelConverter.use_language.use.MultiplicityCS;
import modelConverter.use_language.use.TypedRefCS;
import modelConverter.use_language.use.UsePackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Collection Type CS</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link modelConverter.use_language.use.impl.CollectionTypeCSImpl#getName <em>Name</em>}</li>
 *   <li>{@link modelConverter.use_language.use.impl.CollectionTypeCSImpl#getOwnedType <em>Owned Type</em>}</li>
 *   <li>{@link modelConverter.use_language.use.impl.CollectionTypeCSImpl#getOwnedCollectionMultiplicity <em>Owned Collection Multiplicity</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CollectionTypeCSImpl extends TypedRefCSImpl implements CollectionTypeCS
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getOwnedType() <em>Owned Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedType()
   * @generated
   * @ordered
   */
  protected TypedRefCS ownedType;

  /**
   * The cached value of the '{@link #getOwnedCollectionMultiplicity() <em>Owned Collection Multiplicity</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedCollectionMultiplicity()
   * @generated
   * @ordered
   */
  protected MultiplicityCS ownedCollectionMultiplicity;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CollectionTypeCSImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return UsePackage.Literals.COLLECTION_TYPE_CS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UsePackage.COLLECTION_TYPE_CS__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TypedRefCS getOwnedType()
  {
    return ownedType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetOwnedType(TypedRefCS newOwnedType, NotificationChain msgs)
  {
    TypedRefCS oldOwnedType = ownedType;
    ownedType = newOwnedType;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, UsePackage.COLLECTION_TYPE_CS__OWNED_TYPE, oldOwnedType, newOwnedType);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOwnedType(TypedRefCS newOwnedType)
  {
    if (newOwnedType != ownedType)
    {
      NotificationChain msgs = null;
      if (ownedType != null)
        msgs = ((InternalEObject)ownedType).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - UsePackage.COLLECTION_TYPE_CS__OWNED_TYPE, null, msgs);
      if (newOwnedType != null)
        msgs = ((InternalEObject)newOwnedType).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - UsePackage.COLLECTION_TYPE_CS__OWNED_TYPE, null, msgs);
      msgs = basicSetOwnedType(newOwnedType, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UsePackage.COLLECTION_TYPE_CS__OWNED_TYPE, newOwnedType, newOwnedType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MultiplicityCS getOwnedCollectionMultiplicity()
  {
    return ownedCollectionMultiplicity;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetOwnedCollectionMultiplicity(MultiplicityCS newOwnedCollectionMultiplicity, NotificationChain msgs)
  {
    MultiplicityCS oldOwnedCollectionMultiplicity = ownedCollectionMultiplicity;
    ownedCollectionMultiplicity = newOwnedCollectionMultiplicity;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, UsePackage.COLLECTION_TYPE_CS__OWNED_COLLECTION_MULTIPLICITY, oldOwnedCollectionMultiplicity, newOwnedCollectionMultiplicity);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOwnedCollectionMultiplicity(MultiplicityCS newOwnedCollectionMultiplicity)
  {
    if (newOwnedCollectionMultiplicity != ownedCollectionMultiplicity)
    {
      NotificationChain msgs = null;
      if (ownedCollectionMultiplicity != null)
        msgs = ((InternalEObject)ownedCollectionMultiplicity).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - UsePackage.COLLECTION_TYPE_CS__OWNED_COLLECTION_MULTIPLICITY, null, msgs);
      if (newOwnedCollectionMultiplicity != null)
        msgs = ((InternalEObject)newOwnedCollectionMultiplicity).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - UsePackage.COLLECTION_TYPE_CS__OWNED_COLLECTION_MULTIPLICITY, null, msgs);
      msgs = basicSetOwnedCollectionMultiplicity(newOwnedCollectionMultiplicity, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UsePackage.COLLECTION_TYPE_CS__OWNED_COLLECTION_MULTIPLICITY, newOwnedCollectionMultiplicity, newOwnedCollectionMultiplicity));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case UsePackage.COLLECTION_TYPE_CS__OWNED_TYPE:
        return basicSetOwnedType(null, msgs);
      case UsePackage.COLLECTION_TYPE_CS__OWNED_COLLECTION_MULTIPLICITY:
        return basicSetOwnedCollectionMultiplicity(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case UsePackage.COLLECTION_TYPE_CS__NAME:
        return getName();
      case UsePackage.COLLECTION_TYPE_CS__OWNED_TYPE:
        return getOwnedType();
      case UsePackage.COLLECTION_TYPE_CS__OWNED_COLLECTION_MULTIPLICITY:
        return getOwnedCollectionMultiplicity();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case UsePackage.COLLECTION_TYPE_CS__NAME:
        setName((String)newValue);
        return;
      case UsePackage.COLLECTION_TYPE_CS__OWNED_TYPE:
        setOwnedType((TypedRefCS)newValue);
        return;
      case UsePackage.COLLECTION_TYPE_CS__OWNED_COLLECTION_MULTIPLICITY:
        setOwnedCollectionMultiplicity((MultiplicityCS)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case UsePackage.COLLECTION_TYPE_CS__NAME:
        setName(NAME_EDEFAULT);
        return;
      case UsePackage.COLLECTION_TYPE_CS__OWNED_TYPE:
        setOwnedType((TypedRefCS)null);
        return;
      case UsePackage.COLLECTION_TYPE_CS__OWNED_COLLECTION_MULTIPLICITY:
        setOwnedCollectionMultiplicity((MultiplicityCS)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case UsePackage.COLLECTION_TYPE_CS__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case UsePackage.COLLECTION_TYPE_CS__OWNED_TYPE:
        return ownedType != null;
      case UsePackage.COLLECTION_TYPE_CS__OWNED_COLLECTION_MULTIPLICITY:
        return ownedCollectionMultiplicity != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //CollectionTypeCSImpl
