/**
 * generated by Xtext 2.25.0
 */
package modelConverter.use_language.use.impl;

import modelConverter.use_language.use.SelfExpCS;
import modelConverter.use_language.use.UsePackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Self Exp CS</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SelfExpCSImpl extends ExpCSImpl implements SelfExpCS
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SelfExpCSImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return UsePackage.Literals.SELF_EXP_CS;
  }

} //SelfExpCSImpl
