/**
 * generated by Xtext 2.25.0
 */
package modelConverter.use_language.uml.impl;

import java.util.Collection;

import modelConverter.use_language.uml.InvariantContext;
import modelConverter.use_language.uml.InvariantDefinition;
import modelConverter.use_language.uml.UmlPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Invariant Context</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link modelConverter.use_language.uml.impl.InvariantContextImpl#getVariablename <em>Variablename</em>}</li>
 *   <li>{@link modelConverter.use_language.uml.impl.InvariantContextImpl#getInvariants <em>Invariants</em>}</li>
 * </ul>
 *
 * @generated
 */
public class InvariantContextImpl extends ContextsTypeImpl implements InvariantContext
{
  /**
   * The default value of the '{@link #getVariablename() <em>Variablename</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVariablename()
   * @generated
   * @ordered
   */
  protected static final String VARIABLENAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getVariablename() <em>Variablename</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVariablename()
   * @generated
   * @ordered
   */
  protected String variablename = VARIABLENAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getInvariants() <em>Invariants</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInvariants()
   * @generated
   * @ordered
   */
  protected EList<InvariantDefinition> invariants;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InvariantContextImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return UmlPackage.Literals.INVARIANT_CONTEXT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getVariablename()
  {
    return variablename;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVariablename(String newVariablename)
  {
    String oldVariablename = variablename;
    variablename = newVariablename;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UmlPackage.INVARIANT_CONTEXT__VARIABLENAME, oldVariablename, variablename));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<InvariantDefinition> getInvariants()
  {
    if (invariants == null)
    {
      invariants = new EObjectContainmentEList<InvariantDefinition>(InvariantDefinition.class, this, UmlPackage.INVARIANT_CONTEXT__INVARIANTS);
    }
    return invariants;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case UmlPackage.INVARIANT_CONTEXT__INVARIANTS:
        return ((InternalEList<?>)getInvariants()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case UmlPackage.INVARIANT_CONTEXT__VARIABLENAME:
        return getVariablename();
      case UmlPackage.INVARIANT_CONTEXT__INVARIANTS:
        return getInvariants();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case UmlPackage.INVARIANT_CONTEXT__VARIABLENAME:
        setVariablename((String)newValue);
        return;
      case UmlPackage.INVARIANT_CONTEXT__INVARIANTS:
        getInvariants().clear();
        getInvariants().addAll((Collection<? extends InvariantDefinition>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case UmlPackage.INVARIANT_CONTEXT__VARIABLENAME:
        setVariablename(VARIABLENAME_EDEFAULT);
        return;
      case UmlPackage.INVARIANT_CONTEXT__INVARIANTS:
        getInvariants().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case UmlPackage.INVARIANT_CONTEXT__VARIABLENAME:
        return VARIABLENAME_EDEFAULT == null ? variablename != null : !VARIABLENAME_EDEFAULT.equals(variablename);
      case UmlPackage.INVARIANT_CONTEXT__INVARIANTS:
        return invariants != null && !invariants.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (variablename: ");
    result.append(variablename);
    result.append(')');
    return result.toString();
  }

} //InvariantContextImpl
