/**
 * generated by Xtext 2.25.0
 */
package modelConverter.use_language.uml;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operation Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see modelConverter.use_language.uml.UmlPackage#getOperationType()
 * @model
 * @generated
 */
public interface OperationType extends EObject
{
} // OperationType
