/**
 * generated by Xtext 2.25.0
 */
package modelConverter.use_language.uml;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operation Constraints</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see modelConverter.use_language.uml.UmlPackage#getOperationConstraints()
 * @model
 * @generated
 */
public interface OperationConstraints extends EObject
{
} // OperationConstraints
