/**
 * generated by Xtext 2.25.0
 */
package modelConverter.use_language.uml;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see modelConverter.use_language.uml.UmlPackage
 * @generated
 */
public interface UmlFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  UmlFactory eINSTANCE = modelConverter.use_language.uml.impl.UmlFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Type</em>'.
   * @generated
   */
  Type createType();

  /**
   * Returns a new object of class '<em>Association Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Association Type</em>'.
   * @generated
   */
  AssociationType createAssociationType();

  /**
   * Returns a new object of class '<em>All Class</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>All Class</em>'.
   * @generated
   */
  AllClass createAllClass();

  /**
   * Returns a new object of class '<em>Enumeration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Enumeration</em>'.
   * @generated
   */
  Enumeration createEnumeration();

  /**
   * Returns a new object of class '<em>Owned Literal</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Owned Literal</em>'.
   * @generated
   */
  OwnedLiteral createOwnedLiteral();

  /**
   * Returns a new object of class '<em>Class</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Class</em>'.
   * @generated
   */
  Class createClass();

  /**
   * Returns a new object of class '<em>Association Class</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Association Class</em>'.
   * @generated
   */
  AssociationClass createAssociationClass();

  /**
   * Returns a new object of class '<em>Generalization</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Generalization</em>'.
   * @generated
   */
  Generalization createGeneralization();

  /**
   * Returns a new object of class '<em>Simple Types</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Simple Types</em>'.
   * @generated
   */
  SimpleTypes createSimpleTypes();

  /**
   * Returns a new object of class '<em>Association</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Association</em>'.
   * @generated
   */
  Association createAssociation();

  /**
   * Returns a new object of class '<em>Member End</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Member End</em>'.
   * @generated
   */
  MemberEnd createMemberEnd();

  /**
   * Returns a new object of class '<em>Association Basic</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Association Basic</em>'.
   * @generated
   */
  AssociationBasic createAssociationBasic();

  /**
   * Returns a new object of class '<em>Aggregation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Aggregation</em>'.
   * @generated
   */
  Aggregation createAggregation();

  /**
   * Returns a new object of class '<em>Composition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Composition</em>'.
   * @generated
   */
  Composition createComposition();

  /**
   * Returns a new object of class '<em>Attribute</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Attribute</em>'.
   * @generated
   */
  Attribute createAttribute();

  /**
   * Returns a new object of class '<em>Operation Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Operation Type</em>'.
   * @generated
   */
  OperationType createOperationType();

  /**
   * Returns a new object of class '<em>Operation Basic</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Operation Basic</em>'.
   * @generated
   */
  OperationBasic createOperationBasic();

  /**
   * Returns a new object of class '<em>Operation Complex</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Operation Complex</em>'.
   * @generated
   */
  OperationComplex createOperationComplex();

  /**
   * Returns a new object of class '<em>Operation Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Operation Declaration</em>'.
   * @generated
   */
  OperationDeclaration createOperationDeclaration();

  /**
   * Returns a new object of class '<em>Owned Parameter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Owned Parameter</em>'.
   * @generated
   */
  OwnedParameter createOwnedParameter();

  /**
   * Returns a new object of class '<em>Constraints Base</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Constraints Base</em>'.
   * @generated
   */
  ConstraintsBase createConstraintsBase();

  /**
   * Returns a new object of class '<em>Constrains General</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Constrains General</em>'.
   * @generated
   */
  ConstrainsGeneral createConstrainsGeneral();

  /**
   * Returns a new object of class '<em>Contexts Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Contexts Type</em>'.
   * @generated
   */
  ContextsType createContextsType();

  /**
   * Returns a new object of class '<em>Invariant Context</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Invariant Context</em>'.
   * @generated
   */
  InvariantContext createInvariantContext();

  /**
   * Returns a new object of class '<em>Invariant Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Invariant Definition</em>'.
   * @generated
   */
  InvariantDefinition createInvariantDefinition();

  /**
   * Returns a new object of class '<em>Operation Context</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Operation Context</em>'.
   * @generated
   */
  OperationContext createOperationContext();

  /**
   * Returns a new object of class '<em>Operation Constraints</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Operation Constraints</em>'.
   * @generated
   */
  OperationConstraints createOperationConstraints();

  /**
   * Returns a new object of class '<em>Condition Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Condition Type</em>'.
   * @generated
   */
  ConditionType createConditionType();

  /**
   * Returns a new object of class '<em>Precondition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Precondition</em>'.
   * @generated
   */
  Precondition createPrecondition();

  /**
   * Returns a new object of class '<em>Postcondition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Postcondition</em>'.
   * @generated
   */
  Postcondition createPostcondition();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  UmlPackage getUmlPackage();

} //UmlFactory
