/*
 * generated by Xtext 2.25.0
 */
package modelConverter.use_language.scoping;

import org.eclipse.ocl.xtext.essentialocl.scoping.EssentialOCLScopeProvider;

public abstract class AbstractUSEScopeProvider extends EssentialOCLScopeProvider {
}
