/*
 * generated by Xtext 2.25.0
 */
package modelConverter.use_language.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractUSEScopeProvider extends DelegatingScopeProvider {
}
